# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: array.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='array.proto',
  package='array',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x61rray.proto\x12\x05\x61rray\"3\n\x0c\x41rrayRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x03\x12\x10\n\x04\x64\x61ta\x18\x03 \x03(\x05\x42\x02\x10\x01\"4\n\rArrayResponse\x12\x11\n\tserver_id\x18\x01 \x01(\x03\x12\x10\n\x04\x64\x61ta\x18\x03 \x03(\x05\x42\x02\x10\x01\x32\x90\x01\n\tArrayDemo\x12\x38\n\x0b\x41rrayMethod\x12\x13.array.ArrayRequest\x1a\x14.array.ArrayResponse\x12I\n\x18\x42idirectionalArrayMethod\x12\x13.array.ArrayRequest\x1a\x14.array.ArrayResponse(\x01\x30\x01\x62\x06proto3')
)




_ARRAYREQUEST = _descriptor.Descriptor(
  name='ArrayRequest',
  full_name='array.ArrayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='array.ArrayRequest.client_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='array.ArrayRequest.data', index=1,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=73,
)


_ARRAYRESPONSE = _descriptor.Descriptor(
  name='ArrayResponse',
  full_name='array.ArrayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_id', full_name='array.ArrayResponse.server_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='array.ArrayResponse.data', index=1,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['ArrayRequest'] = _ARRAYREQUEST
DESCRIPTOR.message_types_by_name['ArrayResponse'] = _ARRAYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArrayRequest = _reflection.GeneratedProtocolMessageType('ArrayRequest', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYREQUEST,
  '__module__' : 'array_pb2'
  # @@protoc_insertion_point(class_scope:array.ArrayRequest)
  })
_sym_db.RegisterMessage(ArrayRequest)

ArrayResponse = _reflection.GeneratedProtocolMessageType('ArrayResponse', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYRESPONSE,
  '__module__' : 'array_pb2'
  # @@protoc_insertion_point(class_scope:array.ArrayResponse)
  })
_sym_db.RegisterMessage(ArrayResponse)


_ARRAYREQUEST.fields_by_name['data']._options = None
_ARRAYRESPONSE.fields_by_name['data']._options = None

_ARRAYDEMO = _descriptor.ServiceDescriptor(
  name='ArrayDemo',
  full_name='array.ArrayDemo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=130,
  serialized_end=274,
  methods=[
  _descriptor.MethodDescriptor(
    name='ArrayMethod',
    full_name='array.ArrayDemo.ArrayMethod',
    index=0,
    containing_service=None,
    input_type=_ARRAYREQUEST,
    output_type=_ARRAYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BidirectionalArrayMethod',
    full_name='array.ArrayDemo.BidirectionalArrayMethod',
    index=1,
    containing_service=None,
    input_type=_ARRAYREQUEST,
    output_type=_ARRAYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARRAYDEMO)

DESCRIPTOR.services_by_name['ArrayDemo'] = _ARRAYDEMO

# @@protoc_insertion_point(module_scope)
